SELECT  MANAGER_ID,FIRST_NAME,LAST_NAME , SALARY
FROM EMPLOYEES
WHERE SALARY=3000 AND MANAGER_ID=121;

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN(134,159,183);

SELECT *
FROM EMPLOYEES
WHERE SALARY BETWEEN 1000 AND 3000;

SELECT *
FROM EMPLOYEES
WHERE SALARY <=2500;

SELECT*
FROM EMPLOYEES
WHERE MANAGER_ID NOT BETWEEN 100 AND 200;


SELECT *

FROM EMPLOYEES

WHERE SALARY=(SELECT MAX (SALARY)

FROM EMPLOYEES

 WHERE SALARY < (SELECT MAX (SALARY)

 FROM EMPLOYEES));
 

 SELECT FIRST_NAME, LAST_NAME, HIRE_DATE
 FROM EMPLOYEES
 WHERE NOT FIRST_NAME = 'Clara' AND DEPARTMENT_ID=80;
 
 
 SELECT first_name, last_name, hire_date  
FROM employees  
WHERE department_id =  
( SELECT department_id  
FROM employees  
WHERE first_name = 'Clara')  
AND first_name <> 'Clara';


SELECT employee_id, first_name, last_name  
FROM employees  
WHERE department_id IN  
( SELECT department_id  
FROM employees  
WHERE first_name LIKE '%T%' );
