SELECT last_name, ROUND((SYSDATE-hire_date) / 30 , 0) AS MONTH
FROM employees
WHERE department_id = 90;

SELECT ROUND((SYSDATE-TO_DATE('20-DEC-1995','DD-MON-YYYY')) / 365, 0)AS YEAR FROM DUAL;

SELECT ADD_MONTHS(SYSDATE,10)FROM DUAL;
 
SELECT MONTHS_BETWEEN(SYSDATE,'10-JAN- 97') FROM EMPLOYEES;

SELECT ROUND(SYSDATE,'MONTH') FROM DUAL;
SELECT ROUND(SYSDATE ,'YEAR') FROM DUAL;
SELECT TRUNC(SYSDATE ,'MONTH') FROM DUAL;
SELECT TRUNC(SYSDATE ,'YEAR') FROM DUAL;

SELECT department_id, job_id, SUM(salary)
FROM employees
WHERE department_id > 40
GROUP BY department_id, job_id
ORDER BY department_id;


SELECT JOB_ID, SUM(SALARY) PAYROLL
FROM EMPLOYEES
WHERE JOB_ID NOT LIKE '%REP%'
GROUP BY JOB_ID
HAVING SUM(SALARY)>13000
ORDER BY SUM(SALARY);


SELECT FIRST_NAME, SALARY
FROM EMPLOYEES;
HAVING Salary = (SELECT MAX(Salary) FROM Employees);

ORDER BY Salary DESC


SELECT Name, Salary
FROM Employees
ORDER BY Salary DESC
LIMIT 1;

SELECT Name, Salary
FROM Employees
WHERE Salary = (SELECT MAX(Salary) FROM Employees';



SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY= (SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY< (SELECT MAX (SALARY)
FROM EMPLOYEES
));


