/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package twindow;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Testwindow extends javax.swing.JFrame {

    /**
     * Creates new form Testwindow
     */
    public Testwindow() {
        initComponents();
    }

    //calculate total price
    public float getTotalPrice() {

        float unitPrice = Float.parseFloat(txtunitprice.getText().trim());
        float quatity = Float.parseFloat(txtquantity.getText().trim());

        float totalPrice = unitPrice * quatity;
        return totalPrice;
    }

    public float getDiscount() {
        float totalPrice = getTotalPrice();
        float discount = Float.parseFloat(txtdiscount.getText().trim());
        float discountAmount = totalPrice * discount / 100;

        float actualPrice = totalPrice - discountAmount;

        return actualPrice;
    }
//    
//    public float  getActualPrice(){
//    float totalPrice=getTotalPrice();
//    float discount= Float.parseFloat(txtdiscount.getText().trim());
//    float actualPrice = totalPrice*discount/100;

//    float actualPrice=totalPrice-discountamount;
//    return actualPrice;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnhome = new javax.swing.JButton();
        btnsales = new javax.swing.JButton();
        btnpurchase = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        menu = new javax.swing.JTabbedPane();
        jpanelhome = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sales = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        txtcustomername = new javax.swing.JTextField();
        txtsid = new javax.swing.JTextField();
        txtproductname = new javax.swing.JTextField();
        txtunitprice = new javax.swing.JTextField();
        txtquantity = new javax.swing.JTextField();
        txttotalprice = new javax.swing.JTextField();
        txtdiscount = new javax.swing.JTextField();
        txtactualprice = new javax.swing.JTextField();
        txtcashreceived = new javax.swing.JTextField();
        txtdueaount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtdate = new com.toedter.calendar.JDateChooser();
        purchase = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ORDER INVOICE SYSTEM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 5, 1200, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 100));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnhome.setText("Home");
        btnhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhomeMouseExited(evt);
            }
        });
        jPanel2.add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnsales.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnsales.setText("Sales");
        btnsales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsalesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsalesMouseExited(evt);
            }
        });
        jPanel2.add(btnsales, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        btnpurchase.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnpurchase.setText("Purchase");
        btnpurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpurchaseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpurchaseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpurchaseMouseExited(evt);
            }
        });
        jPanel2.add(btnpurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jButton4.setText("jButton4");
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jButton5.setText("jButton5");
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 110, 580));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Edwardian Script ITC", 3, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Home Menu");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 1080, 70));

        javax.swing.GroupLayout jpanelhomeLayout = new javax.swing.GroupLayout(jpanelhome);
        jpanelhome.setLayout(jpanelhomeLayout);
        jpanelhomeLayout.setHorizontalGroup(
            jpanelhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpanelhomeLayout.setVerticalGroup(
            jpanelhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelhomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(494, Short.MAX_VALUE))
        );

        menu.addTab("tab1", jpanelhome);

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Elephant", 3, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sales Menu");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 1080, 80));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Unit Price");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel6.setText("SID");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel7.setText("Product Name ");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel8.setText("Discount ");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel9.setText("Total Price");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel10.setText("Quantity");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel11.setText("Due Amount ");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel12.setText("Cash Received");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel13.setText("Actual Price");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel15.setText("Customer Name ");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jLabel16.setText("Date");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel11.add(txtcustomername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 400, -1));
        jPanel11.add(txtsid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 400, -1));
        jPanel11.add(txtproductname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 400, -1));

        txtunitprice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtunitpriceFocusLost(evt);
            }
        });
        jPanel11.add(txtunitprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 400, -1));

        txtquantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtquantityFocusLost(evt);
            }
        });
        jPanel11.add(txtquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 400, -1));
        jPanel11.add(txttotalprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 400, -1));

        txtdiscount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdiscountFocusGained(evt);
            }
        });
        txtdiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdiscountKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdiscountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdiscountKeyTyped(evt);
            }
        });
        jPanel11.add(txtdiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 400, -1));
        jPanel11.add(txtactualprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 400, -1));
        jPanel11.add(txtcashreceived, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 400, -1));
        jPanel11.add(txtdueaount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 400, -1));

        jButton1.setText("Submit");
        jPanel11.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, -1, -1));

        jButton2.setText("Reset");
        jPanel11.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, -1, -1));
        jPanel11.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 400, -1));

        javax.swing.GroupLayout salesLayout = new javax.swing.GroupLayout(sales);
        sales.setLayout(salesLayout);
        salesLayout.setHorizontalGroup(
            salesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
            .addGroup(salesLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        salesLayout.setVerticalGroup(
            salesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(salesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)))
        );

        menu.addTab("tab2", sales);

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Elephant", 2, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Purchase Menu");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 1080, 80));

        javax.swing.GroupLayout purchaseLayout = new javax.swing.GroupLayout(purchase);
        purchase.setLayout(purchaseLayout);
        purchaseLayout.setHorizontalGroup(
            purchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        purchaseLayout.setVerticalGroup(
            purchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purchaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(485, Short.MAX_VALUE))
        );

        menu.addTab("tab3", purchase);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1085, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        menu.addTab("tab4", jPanel7);

        jPanel3.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1090, 610));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 1090, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseClicked

        menu.setSelectedIndex(0);

    }//GEN-LAST:event_btnhomeMouseClicked

    private void btnsalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalesMouseClicked
        menu.setSelectedIndex(1);
    }//GEN-LAST:event_btnsalesMouseClicked

    private void btnpurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpurchaseMouseClicked
        menu.setSelectedIndex(2);
    }//GEN-LAST:event_btnpurchaseMouseClicked

    private void btnhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseEntered
        btnhome.setBackground(Color.gray);
    }//GEN-LAST:event_btnhomeMouseEntered

    private void btnhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseExited
        btnhome.setBackground(getBackground());
    }//GEN-LAST:event_btnhomeMouseExited

    private void btnsalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalesMouseEntered
        btnsales.setBackground(Color.gray);
    }//GEN-LAST:event_btnsalesMouseEntered

    private void btnsalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalesMouseExited
        btnsales.setBackground(getBackground());
    }//GEN-LAST:event_btnsalesMouseExited

    private void btnpurchaseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpurchaseMouseEntered
        btnpurchase.setBackground(Color.gray);
    }//GEN-LAST:event_btnpurchaseMouseEntered

    private void btnpurchaseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpurchaseMouseExited
        btnpurchase.setBackground(getBackground());
    }//GEN-LAST:event_btnpurchaseMouseExited

    private void txtunitpriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtunitpriceFocusLost
        try {

            if (!txtunitprice.getText().trim().isEmpty()) {
            } else {
                JOptionPane.showMessageDialog(rootPane, "can not be empty");
                txtunitprice.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "An error occur" + e.getMessage());

        }

    }//GEN-LAST:event_txtunitpriceFocusLost

    private void txtquantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtquantityFocusLost
        try {
            if (txtunitprice.getText().trim().isEmpty()) {
                txtunitprice.requestFocus();
            } else if (!txtquantity.getText().trim().isEmpty()) {
                txttotalprice.setText(getTotalPrice() + "");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Quantity can not be empty");
//                txtquantity.requestFocus();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error" + e.getMessage());

        }
    }//GEN-LAST:event_txtquantityFocusLost

    private void txtdiscountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdiscountFocusGained
        txtdiscount.setText(0 + "");
    }//GEN-LAST:event_txtdiscountFocusGained

    private void txtdiscountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiscountKeyPressed
        txtactualprice.setText(getDiscount() + "");
    }//GEN-LAST:event_txtdiscountKeyPressed

    private void txtdiscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiscountKeyReleased
        txtactualprice.setText(getDiscount() + "");
    }//GEN-LAST:event_txtdiscountKeyReleased

    private void txtdiscountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiscountKeyTyped
        txtactualprice.setText(getDiscount() + "");
    }//GEN-LAST:event_txtdiscountKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Testwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Testwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Testwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Testwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Testwindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnpurchase;
    private javax.swing.JButton btnsales;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jpanelhome;
    private javax.swing.JTabbedPane menu;
    private javax.swing.JPanel purchase;
    private javax.swing.JPanel sales;
    private javax.swing.JTextField txtactualprice;
    private javax.swing.JTextField txtcashreceived;
    private javax.swing.JTextField txtcustomername;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JTextField txtdiscount;
    private javax.swing.JTextField txtdueaount;
    private javax.swing.JTextField txtproductname;
    private javax.swing.JTextField txtquantity;
    private javax.swing.JTextField txtsid;
    private javax.swing.JTextField txttotalprice;
    private javax.swing.JTextField txtunitprice;
    // End of variables declaration//GEN-END:variables
}
